# in _config.yml
title: "Introduction to Data Science for Mechanical Engineers (Lecture Book)"
execute:
  execute_notebooks: "off"
author: "Ilias Bilionis"
launch_buttons:
  colab_url: "https://colab.research.google.com"
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year
